### ISSUE TITLE
incorrect import package on : 6-APIs/Week-1/Exercise 01 Your First API/C6M1L4 Item 05 - Your First API.md

### ISSUE THREAD

**Issue by amirali-safaie** [ShahandFahad/Meta-Back-End-Developer#25]
incorrect import package of model_to_dict in step 11 , it should be ```django.forms.models``` instead of ```django.forms.model```

**Comment by ShahandFahad** [comment]
I've seen it. Thanks for reporting. But these were the default .md files provided for the exercise. That's where it comes form. I will label this as documentation and will look into it.

**Comment by amirali-safaie** [comment]
thanks for your attention
